-- =====================================================================
-- ข้อมูลเมนูแนะนำ (menu_items) — 122 เมนู พร้อมส่วนประกอบ/โภชนาการ/แท็ก
-- Export จากฐานข้อมูล dev ล่าสุด (2026-08-21) ไว้สำหรับนำเข้า production โดยตรง
-- แทนการรัน `npm run seed:menu` บนเซิร์ฟเวอร์ (ซึ่งต้องมี PEXELS_API_KEY
-- และจะไปเรียก Pexels API ใหม่ทั้งหมด — ไฟล์นี้ข้ามขั้นตอนนั้นไปเลย)
--
-- ✅ อัปเดต 2026-08-22: ไฟล์รูป uploads/menu/ (ของ 122 เมนูนี้) ถูก push ขึ้น
-- GitHub มาพร้อมโค้ดแล้ว (เดิมไม่ได้ push เพราะ /uploads ถูก gitignore ทั้งโฟลเดอร์
-- — ตอนนี้เปิดเฉพาะ uploads/menu/ ให้ track เพราะเป็นรูปสต็อกที่แอดมินคัดมา
-- ไม่ใช่ข้อมูลส่วนตัวผู้ใช้) แค่ git pull โค้ดล่าสุดก็จะได้ไฟล์รูปครบ ไม่ต้อง
-- อัปโหลดแยกอีกแล้ว — ขั้นตอนอัปโหลดโฟลเดอร์รูปด้วยมือด้านล่างนี้ไม่จำเป็นอีกต่อไป
--
-- ลำดับการใช้งานที่ถูกต้อง:
--   1) รัน migration-production-2026-08-21.sql ก่อน (สร้างตาราง menu_items เปล่าๆ)
--   2) git pull โค้ดล่าสุด (จะได้ไฟล์รูป uploads/menu/ ทั้งหมดมาด้วย)
--   3) รันไฟล์นี้ (เติมข้อมูล 122 แถว) แล้วตามด้วย menu-items-seed-2026-08-22.sql
--      (อีก 55 เมนูใหม่ รวมเป็น 177 เมนู)
--
-- ถ้าตาราง menu_items มีข้อมูลอยู่แล้ว (เช่นเคยรัน seed:menu ไปแล้ว) อย่ารันไฟล์นี้ซ้ำ
-- จะชนกับ id เดิมและ error — ต้องลบข้อมูลเก่าในตารางนี้ก่อน หรือข้ามไฟล์นี้ไปเลย
-- =====================================================================
-- MariaDB dump 10.19  Distrib 10.4.28-MariaDB, for Win64 (AMD64)
--
-- Host: localhost    Database: trainner
-- ------------------------------------------------------
-- Server version	10.4.28-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `menu_items`
--

LOCK TABLES `menu_items` WRITE;
/*!40000 ALTER TABLE `menu_items` DISABLE KEYS */;
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (1,'อกไก่ย่างสมุนไพร สลัดผัก','อกไก่ย่างหมักสมุนไพร เสิร์ฟกับสลัดผักรวมน้ำสลัดใส','1787222042034-f29ad46480f4.webp','ภาพโดย Mohamed  Olwy จาก Pexels',320,38,12,10,1,1,'LUNCH',1,'2026-08-20 08:00:42','[\"อกไก่ 150 กรัม\",\"ผักสลัดรวม\",\"มะเขือเทศเชอร์รี่\",\"แตงกวา\",\"น้ำสลัดใส\",\"สมุนไพรหมัก\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (2,'ข้าวกล้องผัดกะเพราไก่ไข่ดาว (น้ำมันน้อย)','ผัดกะเพราไก่สับสูตรน้ำมันน้อย เสิร์ฟกับข้าวกล้องและไข่ดาว','1787212843192-a5bfdc957ec9.webp','ภาพโดย Manav Chahal จาก Pexels',480,32,55,14,1,0,'LUNCH',1,'2026-08-20 08:00:43','[\"ไก่สับ 120 กรัม\",\"ใบกะเพรา\",\"ข้าวกล้อง 1 ทัพพี\",\"ไข่ดาว 1 ฟอง\",\"พริก/กระเทียม\",\"ซอสปรุงรส\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (3,'ต้มยำกุ้งน้ำใส','ต้มยำกุ้งสูตรน้ำใส เผ็ดเปรี้ยวจัดจ้าน ไม่ใส่นม','1787212844396-a7ee36ade539.webp','ภาพโดย JANG \'S 🍂 จาก Pexels',180,20,10,5,1,1,'DINNER',1,'2026-08-20 08:00:44','[\"กุ้ง 100 กรัม\",\"ตะไคร้\",\"ใบมะกรูด\",\"ข่า\",\"พริกขี้หนู\",\"น้ำมะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (4,'ยำวุ้นเส้นทะเล','ยำวุ้นเส้นรวมมิตรทะเล กุ้ง หมึก เผ็ดเปรี้ยว','1787212845872-263f706d4362.webp','ภาพโดย nana liu จาก Pexels',250,18,28,6,1,1,'DINNER',1,'2026-08-20 08:00:45','[\"วุ้นเส้น\",\"กุ้งสด\",\"หมึกสด\",\"หอมใหญ่\",\"คื่นฉ่าย\",\"น้ำยำรสจัด\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (5,'ข้าวโอ๊ตต้มนมอัลมอนด์ กล้วย','ข้าวโอ๊ตต้มกับนมอัลมอนด์ ใส่กล้วยหั่นและอบเชย','1787212847002-ae9ea87d6f57.webp','ภาพโดย Наталья Масик จาก Pexels',300,10,55,6,1,0,'BREAKFAST',1,'2026-08-20 08:00:47','[\"ข้าวโอ๊ต 50 กรัม\",\"นมอัลมอนด์\",\"กล้วยหอม\",\"อบเชย\",\"น้ำผึ้งเล็กน้อย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (7,'สลัดทูน่าไข่ต้ม','ทูน่าในน้ำแร่ ไข่ต้ม ผักสลัดรวม น้ำสลัดใส','1787212849186-114cfb19ba71.webp','ภาพโดย Gonzalo Mendiola จาก Pexels',280,26,12,14,1,1,'LUNCH',1,'2026-08-20 08:00:49','[\"ทูน่าในน้ำแร่\",\"ไข่ต้ม\",\"ผักสลัดรวม\",\"มะเขือเทศ\",\"น้ำสลัดใส\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (8,'แซลมอนย่างซอสเทอริยากิ บร็อคโคลี่นึ่ง','แซลมอนย่างราดซอสเทอริยากิ เสิร์ฟกับบร็อคโคลี่นึ่ง','1787212850317-1ae687299dbc.webp','ภาพโดย Romjan Aly จาก Pexels',420,34,20,20,1,0,'DINNER',1,'2026-08-20 08:00:50','[\"แซลมอน 150 กรัม\",\"ซอสเทอริยากิ\",\"บร็อคโคลี่นึ่ง\",\"งาขาว\",\"ข้าวสวย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (9,'สลัดอกไก่ควินัว','อกไก่ย่างหั่นชิ้น ควินัวต้ม ผักสลัดรวม','1787212851396-7d2f9a118972.webp','ภาพโดย Loren Castillo จาก Pexels',380,30,35,12,1,0,'LUNCH',1,'2026-08-20 08:00:51','[\"อกไก่ย่าง\",\"ควินัวต้ม\",\"ผักสลัดรวม\",\"มะเขือเทศเชอร์รี่\",\"น้ำสลัดมะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (10,'ข้าวผัดไข่ขาวใส่ผัก สูตรแคลต่ำ','ข้าวผัดไข่ขาว ใส่ผักรวม ปรุงรสน้ำมันน้อย','1787212852468-368c04a47b69.webp','ภาพโดย I Own My Food Art จาก Pexels',300,14,45,6,0,1,'LUNCH',1,'2026-08-20 08:00:52','[\"ไข่ขาว 3 ฟอง\",\"ข้าวสวย\",\"แครอท\",\"ถั่วลันเตา\",\"ต้นหอม\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (11,'ส้มตำไทย (ไม่ใส่น้ำตาลปี๊บ)','ส้มตำไทยรสจัดจ้าน สูตรลดหวาน ไม่ใส่น้ำตาลปี๊บ','1787212853581-80ae26553017.webp','ภาพโดย Romjan Aly จาก Pexels',120,4,22,2,0,1,'SNACK',1,'2026-08-20 08:00:53','[\"มะละกอสับ\",\"มะเขือเทศ\",\"ถั่วฝักยาว\",\"กระเทียม/พริก\",\"มะนาว\",\"น้ำปลา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (12,'แกงจืดเต้าหู้หมูสับ','แกงจืดเต้าหู้อ่อนหมูสับ ใส่ผักกาดขาว','1787212854694-c440765cfd08.webp','ภาพโดย Cook Eat จาก Pexels',220,18,10,10,1,1,'DINNER',1,'2026-08-20 08:00:54','[\"เต้าหู้อ่อน\",\"หมูสับ\",\"ผักกาดขาว\",\"กระเทียม\",\"ต้นหอม/ผักชี\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (13,'ปลานึ่งมะนาว ข้าวกล้อง','ปลากะพงนึ่งมะนาว รสเปรี้ยวเผ็ด เสิร์ฟกับข้าวกล้อง','1787212856002-cf0d95d663cf.webp','ภาพโดย Anna Tarazevich จาก Pexels',380,32,40,8,1,0,'DINNER',1,'2026-08-20 08:00:56','[\"ปลากะพง\",\"มะนาว\",\"กระเทียม/พริก\",\"ผักชี\",\"ข้าวกล้อง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (14,'โยเกิร์ตกรีก เบอร์รี่ กราโนล่า','โยเกิร์ตกรีกไขมันต่ำ ใส่เบอร์รี่รวมและกราโนล่า','1787212857404-737113ee3604.webp','ภาพโดย Jared Kaeb จาก Pexels',230,15,30,6,1,1,'BREAKFAST',1,'2026-08-20 08:00:57','[\"โยเกิร์ตกรีก\",\"บลูเบอร์รี่\",\"สตรอว์เบอร์รี่\",\"กราโนล่า\",\"น้ำผึ้ง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (15,'สมูทตี้โบวล์ผลไม้รวม','สมูทตี้โบวล์ปั่นจากผลไม้รวม โรยหน้าด้วยธัญพืช','1787212858247-c2894039a354.webp','ภาพโดย Наталья Масик จาก Pexels',310,8,55,8,1,0,'BREAKFAST',1,'2026-08-20 08:00:58','[\"กล้วยแช่แข็ง\",\"เบอร์รี่รวม\",\"นมอัลมอนด์\",\"เมล็ดเจีย\",\"กราโนล่า\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (16,'ไก่อบสมุนไพร มันหวานอบ','อกไก่อบสมุนไพรทั้งชิ้น เสิร์ฟกับมันหวานอบ','1787212859580-626dc15a1ddf.webp','ภาพโดย TheWolf Studio จาก Pexels',400,35,35,12,1,0,'DINNER',1,'2026-08-20 08:00:59','[\"อกไก่ทั้งชิ้น\",\"โรสแมรี่/ไทม์\",\"มันหวาน\",\"น้ำมันมะกอก\",\"กระเทียม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (17,'สลัดผักรวมน้ำสลัดงา','ผักสลัดรวมสด ราดน้ำสลัดงาแคลต่ำ','1787212860811-73a32696de9d.webp','ภาพโดย Ahmed Mohamed  AbdElfattah จาก Pexels',150,5,15,8,0,1,'SNACK',1,'2026-08-20 08:01:00','[\"ผักสลัดรวม\",\"แครอทเส้น\",\"ข้าวโพดอ่อน\",\"น้ำสลัดงา\",\"งาคั่ว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (18,'ข้าวต้มปลา','ข้าวต้มปลากะพง ใส่ขิงและต้นหอม','1787212861921-1eacf356e48b.webp','ภาพโดย Kenneth Surillo จาก Pexels',250,20,30,5,0,1,'BREAKFAST',1,'2026-08-20 08:01:02','[\"ปลากะพง\",\"ข้าวสวย\",\"ขิงซอย\",\"ต้นหอม/ผักชี\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (19,'อกไก่นึ่งงาดำ ผักลวก','อกไก่นึ่งโรยงาดำ เสิร์ฟกับผักลวกรวม','1787212863135-6e1dfa6888f9.webp','ภาพโดย Christina Voinova จาก Pexels',260,30,15,8,1,1,'LUNCH',1,'2026-08-20 08:01:03','[\"อกไก่นึ่ง\",\"งาดำ\",\"บร็อคโคลี่ลวก\",\"แครอทลวก\",\"ซอสงา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (20,'ซุปฟักทองนมอัลมอนด์','ซุปฟักทองบดเนียน ผสมนมอัลมอนด์ ไม่ใส่ครีม','1787212864223-992128c54182.webp','ภาพโดย Farhad Ibrahimzade จาก Pexels',160,5,25,5,1,1,'SNACK',1,'2026-08-20 08:01:04','[\"ฟักทอง\",\"นมอัลมอนด์\",\"หอมใหญ่\",\"เกลือ/พริกไทย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (21,'กุ้งอบเนย หน่อไม้ฝรั่ง','กุ้งแม่น้ำอบเนยกระเทียม เสิร์ฟกับหน่อไม้ฝรั่ง','1787212865588-1c7774fb5c06.webp','ภาพโดย Roken Manases จาก Pexels',340,28,10,20,1,0,'DINNER',1,'2026-08-20 08:01:05','[\"กุ้งแม่น้ำ\",\"เนย\",\"กระเทียม\",\"หน่อไม้ฝรั่ง\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (22,'ข้าวไข่เจียวไข่ขาว น้ำมันน้อย','ไข่เจียวไข่ขาวทอดน้ำมันน้อย เสิร์ฟกับข้าวสวย','1787212866861-1da70bca9025.webp','ภาพโดย J KREATOR จาก Pexels',280,16,40,6,0,1,'LUNCH',1,'2026-08-20 08:01:06','[\"ไข่ขาว 3 ฟอง\",\"ข้าวสวย\",\"ต้นหอม\",\"ซอสพริก\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (23,'สลัดผลไม้รวม ไม่ใส่น้ำเชื่อม','ผลไม้รวมตามฤดูกาล หั่นพร้อมทาน ไม่ใส่น้ำเชื่อม','1787212867921-cbdc48ea865f.webp','ภาพโดย Ana Palade จาก Pexels',140,2,34,1,0,1,'SNACK',1,'2026-08-20 08:01:08','[\"แอปเปิล\",\"องุ่น\",\"แคนตาลูป\",\"สับปะรด\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (24,'อกไก่ย่างซอสพริกไทยดำ ข้าวกล้อง','อกไก่ย่างราดซอสพริกไทยดำ เสิร์ฟกับข้าวกล้อง','1787212869039-467353628515.webp','ภาพโดย Kenneth Surillo จาก Pexels',420,36,40,10,1,0,'LUNCH',1,'2026-08-20 08:01:09','[\"อกไก่ย่าง\",\"ซอสพริกไทยดำ\",\"ข้าวกล้อง\",\"บร็อคโคลี่\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (25,'แกงเลียงผักรวม','แกงเลียงผักรวมรสเผ็ดร้อน ใส่กุ้งแห้ง','1787212870197-70fe6ced7cbc.webp','ภาพโดย Rahul Sonawane จาก Pexels',180,10,18,6,1,1,'DINNER',1,'2026-08-20 08:01:10','[\"ฟักทอง\",\"บวบ\",\"ตำลึง\",\"กุ้งแห้ง\",\"พริกไทย/หอมแดง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (26,'เต้าหู้ผัดผักรวม น้ำมันน้อย','เต้าหู้ทอดน้ำมันน้อยผัดกับผักรวม','1787212871238-43c4770689c5.webp','ภาพโดย Kunal Lakhotia จาก Pexels',240,14,20,10,1,1,'DINNER',1,'2026-08-20 08:01:11','[\"เต้าหู้แข็ง\",\"แครอท\",\"ถั่วลันเตา\",\"ข้าวโพดอ่อน\",\"ซอสหอยนางรม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (27,'ไข่ตุ๋นทรงเครื่อง','ไข่ตุ๋นนุ่มใส่หมูสับและต้นหอม','1787212872331-44f75994c1db.webp','ภาพโดย Bytes for Food จาก Pexels',200,14,8,12,0,1,'DINNER',1,'2026-08-20 08:01:12','[\"ไข่ไก่ 2 ฟอง\",\"หมูสับ\",\"เห็ดหอม\",\"ต้นหอม\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (28,'น้ำเต้าหู้ไม่หวาน ธัญพืช','น้ำเต้าหู้สูตรไม่หวาน โรยหน้าด้วยธัญพืชรวม','1787212873679-676d0868a238.webp','ภาพโดย Nalin Costha จาก Pexels',150,8,20,4,0,1,'BREAKFAST',1,'2026-08-20 08:01:13','[\"น้ำเต้าหู้\",\"ข้าวโอ๊ต\",\"เมล็ดฟักทอง\",\"อัลมอนด์สไลซ์\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (29,'สเต็กแซลมอนซอสมะนาว','สเต็กแซลมอนย่าง ราดซอสมะนาวเนย','1787212874963-7c34bdbb279f.webp','ภาพโดย dam i จาก Pexels',400,32,15,22,1,0,'DINNER',1,'2026-08-20 08:01:15','[\"แซลมอนสเต็ก\",\"เนย\",\"มะนาว\",\"กระเทียม\",\"ผักโขม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (30,'ข้าวกล้องผัดผักรวมเต้าหู้','ข้าวกล้องผัดผักรวมใส่เต้าหู้ น้ำมันน้อย','1787212876244-b0a181662110.webp','ภาพโดย Keegan Evans จาก Pexels',320,15,45,8,1,1,'LUNCH',1,'2026-08-20 08:01:16','[\"ข้าวกล้อง\",\"เต้าหู้\",\"แครอท\",\"ถั่วลันเตา\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (31,'ไก่ต้มขมิ้น น้ำจิ้มแจ่ว','ไก่ต้มขมิ้นทั้งตัว หั่นเสิร์ฟกับน้ำจิ้มแจ่วรสแซ่บ','1787212877577-7d73b024a30d.webp','ภาพโดย Cook Eat จาก Pexels',260,32,8,10,1,1,'LUNCH',1,'2026-08-20 08:01:17','[\"ไก่ทั้งตัว\",\"ขมิ้นสด\",\"ตะไคร้\",\"น้ำจิ้มแจ่ว\",\"ผักแนม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (32,'เมี่ยงคำ แคลต่ำ','เมี่ยงคำห่อใบชะพลู รสจัดจ้าน ของว่างแคลต่ำ','1787212878626-f231c376b318.webp','ภาพโดย Anna Tarazevich จาก Pexels',130,5,15,5,0,1,'SNACK',1,'2026-08-20 08:01:18','[\"ใบชะพลู\",\"มะพร้าวคั่ว\",\"ถั่วลิสง\",\"ขิงซอย\",\"มะนาว\",\"น้ำเมี่ยงคำ\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (34,'ไข่ต้ม อะโวคาโดโทสต์โฮลวีท','ไข่ต้ม 2 ฟอง คู่ขนมปังโฮลวีททาอะโวคาโด','1787213024084-0ded49f3a496.webp','ภาพโดย Tima Miroshnichenko จาก Pexels',340,16,30,18,1,0,'BREAKFAST',1,'2026-08-20 08:03:44','[\"ไข่ต้ม 2 ฟอง\",\"ขนมปังโฮลวีท\",\"อะโวคาโด\",\"มะนาว\",\"เกลือ/พริกไทย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (35,'ผัดไทยกุ้งสด น้ำมันน้อย','ผัดไทยเส้นจันท์สูตรน้ำมันน้อย ใส่กุ้งสด ถั่วงอก','1787213847742-4acc6602d481.webp','ภาพโดย Cook Eat จาก Pexels',420,24,55,12,0,1,'LUNCH',1,'2026-08-20 08:17:27','[\"เส้นจันท์\",\"กุ้งสด\",\"ถั่วงอก\",\"ไข่\",\"ถั่วลิสงป่น\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (36,'ก๋วยเตี๋ยวต้มยำน้ำใส','ก๋วยเตี๋ยวหมูต้มยำน้ำใส รสเปรี้ยวเผ็ดจัดจ้าน','1787213849057-99e69fbec6af.webp','ภาพโดย Khải Nguyễn Thanh จาก Pexels',280,15,40,6,1,1,'LUNCH',1,'2026-08-20 08:17:29','[\"เส้นก๋วยเตี๋ยว\",\"หมูสไลซ์\",\"ตะไคร้/ใบมะกรูด\",\"พริกป่น\",\"น้ำมะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (37,'ข้าวมันไก่ต้ม (ไม่ใส่หนัง)','ข้าวมันไก่ต้มแบบลอกหนังออก น้ำจิ้มแจ่วพริกขิง','1787213850183-ef236164519f.webp','ภาพโดย Vicky Tran จาก Pexels',450,30,55,10,1,0,'LUNCH',1,'2026-08-20 08:17:30','[\"ไก่ต้ม (ไม่มีหนัง)\",\"ข้าวหุงน้ำมันไก่\",\"ขิง/กระเทียม\",\"น้ำจิ้มแจ่ว\",\"แตงกวา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (38,'แกงส้มผักรวมกุ้ง','แกงส้มรสจัดจ้าน ใส่ผักรวมและกุ้งสด','1787213851205-72bd4af227bd.webp','ภาพโดย Anna Tarazevich จาก Pexels',200,16,18,5,1,1,'DINNER',1,'2026-08-20 08:17:31','[\"กุ้งสด\",\"มะละกอ/ผักกาดขาว\",\"พริกแกงส้ม\",\"มะขามเปียก\",\"น้ำปลา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (39,'แกงเขียวหวานไก่ กะทิน้อย','แกงเขียวหวานไก่สูตรลดกะทิ ใส่มะเขือพวง','1787213852359-f75209b3f192.webp','ภาพโดย aboodi vesakaran จาก Pexels',380,28,20,20,1,0,'DINNER',1,'2026-08-20 08:17:32','[\"ไก่\",\"พริกแกงเขียวหวาน\",\"กะทิ (น้อย)\",\"มะเขือพวง\",\"ใบโหระพา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (40,'ลาบไก่','ลาบไก่สับรสแซ่บ ใส่ข้าวคั่วและสะระแหน่','1787213853628-1b0ccebf186f.webp','ภาพโดย Bia Metidieri จาก Pexels',260,28,10,10,1,1,'DINNER',1,'2026-08-20 08:17:33','[\"ไก่สับ\",\"ข้าวคั่ว\",\"พริกป่น\",\"หอมแดง\",\"สะระแหน่\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (41,'น้ำตกหมู','หมูย่างสไลซ์คลุกน้ำตก รสเปรี้ยวเผ็ดจัดจ้าน','1787213854928-d85364b1ad8f.webp','ภาพโดย Иван Григорьев จาก Pexels',280,26,8,14,0,1,'DINNER',1,'2026-08-20 08:17:35','[\"หมูย่าง\",\"ข้าวคั่ว\",\"พริกป่น\",\"หอมแดง\",\"ผักชีฝรั่ง\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (42,'หมูย่างซอสมะขาม ข้าวกล้อง','หมูย่างราดซอสมะขามเปียก เสิร์ฟกับข้าวกล้อง','1787213856284-c81a20edeb99.webp','ภาพโดย Malte Luk จาก Pexels',400,30,40,12,1,0,'LUNCH',1,'2026-08-20 08:17:36','[\"หมูสันคอ\",\"ซอสมะขามเปียก\",\"ข้าวกล้อง\",\"ผักสด\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (43,'ปลาทูทอด น้ำพริกผักลวก','ปลาทูทอดคู่น้ำพริกกะปิและผักลวกรวม','1787213857569-1899513af531.webp','ภาพโดย Tamba Budiarsana จาก Pexels',320,24,20,16,1,0,'LUNCH',1,'2026-08-20 08:17:37','[\"ปลาทู\",\"น้ำพริกกะปิ\",\"ผักลวกรวม\",\"มะเขือ\",\"แตงกวา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (44,'ข้าวคลุกกะปิ','ข้าวคลุกกะปิรสเข้มข้น เสิร์ฟกับไข่เจียวและหมูหวาน','1787213858758-24e15cd790ea.webp','ภาพโดย Nay Nyo จาก Pexels',380,18,50,12,0,0,'LUNCH',1,'2026-08-20 08:17:38','[\"กะปิ\",\"ข้าวสวย\",\"หมูหวาน\",\"ไข่เจียวซอย\",\"ถั่วฝักยาว\",\"มะม่วงเปรี้ยว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (45,'ข้าวผัดแซลมอนคลีน','ข้าวผัดแซลมอนสูตรคลีน ใส่ผักรวมน้ำมันน้อย','1787213859857-fd9dd40e57c7.webp','ภาพโดย Josh Eleazar จาก Pexels',420,26,48,14,1,0,'LUNCH',1,'2026-08-20 08:17:39','[\"แซลมอน\",\"ข้าวกล้อง\",\"ไข่\",\"ต้นหอม\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (46,'สลัดโรลเวียดนามกุ้ง','สลัดโรลเวียดนามสด ใส่กุ้งและวุ้นเส้น จิ้มน้ำจิ้มถั่ว','1787213861073-af759e93a6dc.webp','ภาพโดย Arya Bajra จาก Pexels',180,12,28,2,1,1,'SNACK',1,'2026-08-20 08:17:41','[\"แผ่นเปาะเปี๊ยะ\",\"กุ้งลวก\",\"วุ้นเส้น\",\"ผักสด/สะระแหน่\",\"น้ำจิ้มถั่ว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (47,'เกี๊ยวซ่าไก่นึ่ง','เกี๊ยวซ่าไก่สับนึ่ง เสิร์ฟกับน้ำจิ้มซีอิ๊ว','1787213862242-c10043f3e17c.webp','ภาพโดย tanish  pathania จาก Pexels',220,14,25,7,0,1,'SNACK',1,'2026-08-20 08:17:42','[\"ไก่สับ\",\"แป้งเกี๊ยว\",\"กะหล่ำปลี\",\"ขิง\",\"น้ำจิ้มซีอิ๊ว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (48,'ข้าวหน้าไก่สไตล์ญี่ปุ่น (ลดน้ำมัน)','โอยาโกะดงไก่ไข่ สูตรลดน้ำมัน เสิร์ฟกับข้าวสวย','1787213863353-e2f9905ebe33.webp','ภาพโดย Josh Eleazar จาก Pexels',440,28,55,12,0,0,'LUNCH',1,'2026-08-20 08:17:43','[\"ไก่สไลซ์\",\"ไข่\",\"หอมใหญ่\",\"ซอสดาชิ\",\"ข้าวสวย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (49,'ซาชิมิรวม','ซาชิมิปลาแซลมอนและทูน่ารวม เสิร์ฟเย็น','1787213864755-8c84416a2167.webp','ภาพโดย Mony  Cruz จาก Pexels',220,32,4,8,1,1,'DINNER',1,'2026-08-20 08:17:44','[\"แซลมอนสด\",\"ทูน่าสด\",\"วาซาบิ\",\"โชยุ\",\"ขิงดอง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (50,'โอนิกิริไข่ปลา','ข้าวปั้นโอนิกิริห่อสาหร่าย ไส้ไข่ปลา','1787213865844-6ebb3badde60.webp','ภาพโดย Alma Galangco จาก Pexels',180,6,34,2,0,1,'SNACK',1,'2026-08-20 08:17:45','[\"ข้าวสวย\",\"ไข่ปลา\",\"สาหร่ายโนริ\",\"งา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (51,'สลัดโรลผักรวมเต้าหู้','สลัดโรลเวียดนามผักรวมและเต้าหู้ จิ้มน้ำจิ้มถั่ว','1787213867211-2510680d4e98.webp','ภาพโดย Arya Bajra จาก Pexels',150,8,20,4,1,1,'SNACK',1,'2026-08-20 08:17:47','[\"แผ่นเปาะเปี๊ยะ\",\"เต้าหู้ทอด\",\"แครอท/แตงกวา\",\"วุ้นเส้น\",\"น้ำจิ้มถั่ว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (52,'ซุปมิโสะเต้าหู้สาหร่าย','ซุปมิโสะร้อนใส่เต้าหู้อ่อนและสาหร่ายวากาเมะ','1787213868044-3189f0a5c97a.webp','ภาพโดย Cook Eat จาก Pexels',90,6,8,3,1,1,'SNACK',1,'2026-08-20 08:17:48','[\"มิโสะ\",\"เต้าหู้อ่อน\",\"สาหร่ายวากาเมะ\",\"ต้นหอม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (53,'ยำถั่วพูกุ้งสด','ยำถั่วพูกรอบใส่กุ้งสด รสเปรี้ยวเผ็ด','1787213869366-d081b357b9d9.webp','ภาพโดย Ilyas Chabli จาก Pexels',200,16,15,8,1,1,'LUNCH',1,'2026-08-20 08:17:49','[\"ถั่วพู\",\"กุ้งลวก\",\"หอมแดง\",\"พริกขี้หนู\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (54,'แกงป่าไก่','แกงป่าไก่รสจัดจ้าน ไม่ใส่กะทิ ใส่ผักรวม','1787213870705-1b4fa9dbb2a6.webp','ภาพโดย Kunal Lakhotia จาก Pexels',220,26,10,8,1,1,'DINNER',1,'2026-08-20 08:17:50','[\"ไก่\",\"พริกแกงป่า\",\"หน่อไม้\",\"ใบมะกรูด\",\"พริกไทยอ่อน\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (55,'ต้มข่าไก่ นมข้นน้อย','ต้มข่าไก่สูตรลดนมข้น รสเปรี้ยวเผ็ดกลมกล่อม','1787213871815-af754608aedc.webp','ภาพโดย Farhad Ibrahimzade จาก Pexels',260,20,12,15,1,0,'DINNER',1,'2026-08-20 08:17:51','[\"ไก่\",\"ข่า/ตะไคร้\",\"นมข้นจืด (น้อย)\",\"เห็ดฟาง\",\"ใบมะกรูด\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (56,'ผัดผักบุ้งไฟแดงกุ้ง','ผักบุ้งไฟแดงผัดกับกุ้งสด น้ำมันน้อย','1787213873157-c3bc82cd3d2f.webp','ภาพโดย Mohamed  Olwy จาก Pexels',180,14,12,9,1,1,'DINNER',1,'2026-08-20 08:17:53','[\"ผักบุ้ง\",\"กุ้งสด\",\"กระเทียม/พริก\",\"ซอสหอยนางรม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (57,'ไก่อบสมุนไพรไม่ทอด','น่องไก่อบสมุนไพรไม่ใช้น้ำมันทอด หนังกรอบ','1787213874412-1d0fd4f29b28.webp','ภาพโดย Loren Castillo จาก Pexels',340,34,15,14,1,0,'LUNCH',1,'2026-08-20 08:17:54','[\"น่องไก่\",\"โรสแมรี่\",\"กระเทียม\",\"น้ำมันมะกอกเล็กน้อย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (58,'ปอเปี๊ยะสดกุ้ง','ปอเปี๊ยะสดไส้กุ้งและผักสด จิ้มน้ำจิ้มบ๊วย','1787213875368-d4eee26197ae.webp','ภาพโดย Arya Bajra จาก Pexels',160,10,25,2,1,1,'SNACK',1,'2026-08-20 08:17:55','[\"แผ่นเปาะเปี๊ยะ\",\"กุ้งลวก\",\"ผักสลัด\",\"เส้นหมี่\",\"น้ำจิ้มบ๊วย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (59,'เต้าหู้อบกรอบ น้ำจิ้มสุกี้','เต้าหู้อบกรอบแทนการทอด เสิร์ฟกับน้ำจิ้มสุกี้','1787213876730-47841907de5e.webp','ภาพโดย Jay Abrantes จาก Pexels',200,12,18,9,0,1,'SNACK',1,'2026-08-20 08:17:56','[\"เต้าหู้แข็ง\",\"แป้งทอดกรอบ\",\"น้ำจิ้มสุกี้\",\"ผักชี\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (60,'สุกี้น้ำทะเลรวม','สุกี้น้ำใส่อาหารทะเลรวม วุ้นเส้น และผัก','1787213877690-071f67d8de2e.webp','ภาพโดย JANG \'S 🍂 จาก Pexels',260,28,20,6,1,1,'DINNER',1,'2026-08-20 08:17:57','[\"กุ้ง/หมึก/ปลา\",\"วุ้นเส้น\",\"ผักรวม\",\"น้ำซุปสุกี้\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (61,'ข้าวต้มกุ้ง','ข้าวต้มกุ้งสด ใส่ขิงซอยและต้นหอม','1787213878857-d2623589b76c.webp','ภาพโดย salah amrani จาก Pexels',240,18,32,4,0,1,'BREAKFAST',1,'2026-08-20 08:17:58','[\"กุ้งสด\",\"ข้าวสวย\",\"ขิงซอย\",\"ต้นหอม/ผักชี\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (62,'โจ๊กหมูใส่ไข่','โจ๊กหมูสับใส่ไข่ลวก โรยขิงซอย','1787213880163-7dd9d9c79352.webp','ภาพโดย J KREATOR จาก Pexels',280,16,35,8,0,0,'BREAKFAST',1,'2026-08-20 08:18:00','[\"หมูสับ\",\"ข้าวต้ม\",\"ไข่ลวก\",\"ขิงซอย\",\"ต้นหอม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (63,'แพนเค้กกล้วยโปรตีน','แพนเค้กแป้งโฮลวีทผสมกล้วยและเวย์โปรตีน','1787213881253-eaf42d57d1c4.webp','ภาพโดย Ana Palade จาก Pexels',320,20,40,8,1,0,'BREAKFAST',1,'2026-08-20 08:18:01','[\"แป้งโฮลวีท\",\"กล้วยหอม\",\"เวย์โปรตีน\",\"ไข่\",\"นมจืด\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (64,'แซนวิชไข่ขนมปังธัญพืช','แซนวิชไข่ต้มบดผสมมัสตาร์ด ขนมปังโฮลวีท','1787213882398-ed091f3a8cc8.webp','ภาพโดย Jane  T D. จาก Pexels',300,16,32,12,0,0,'BREAKFAST',1,'2026-08-20 08:18:02','[\"ไข่ต้มบด\",\"มัสตาร์ด\",\"ขนมปังโฮลวีท\",\"ผักกาดหอม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (65,'มัฟฟินไข่ผักรวม','มัฟฟินไข่อบใส่ผักรวม โปรตีนสูง แคลต่ำ','1787213883601-54dc2c9cc24f.webp','ภาพโดย Vedih  Akbaş จาก Pexels',220,16,10,13,1,1,'BREAKFAST',1,'2026-08-20 08:18:03','[\"ไข่\",\"พริกหวาน\",\"หอมใหญ่\",\"ผักโขม\",\"ชีสไขมันต่ำ\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (66,'คุกกี้ข้าวโอ๊ตกล้วย ไม่ใส่แป้ง','คุกกี้ข้าวโอ๊ตผสมกล้วยบด อบไม่ใส่แป้งสาลี','1787213884850-62c7da72d531.webp','ภาพโดย Arts Dianti จาก Pexels',150,4,26,4,1,1,'SNACK',1,'2026-08-20 08:18:04','[\"ข้าวโอ๊ต\",\"กล้วยบด\",\"อบเชย\",\"ลูกเกด\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (67,'พุดดิ้งเมล็ดเจียผลไม้','พุดดิ้งเมล็ดเจียแช่นมอัลมอนด์ ท็อปด้วยผลไม้สด','1787213885975-26973f00990c.webp','ภาพโดย İdil Ceren Çelikler จาก Pexels',180,6,24,7,1,1,'SNACK',1,'2026-08-20 08:18:06','[\"เมล็ดเจีย\",\"นมอัลมอนด์\",\"น้ำผึ้ง\",\"ผลไม้สด\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (68,'กล้วยหอมเนยถั่ว','กล้วยหอมหั่นทาเนยถั่วธรรมชาติ','1787213887100-f61dd6a77678.webp','ภาพโดย İdil Ceren Çelikler จาก Pexels',210,6,28,9,1,0,'SNACK',1,'2026-08-20 08:18:07','[\"กล้วยหอม\",\"เนยถั่วธรรมชาติ\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (69,'ข้าวโพดต้ม','ข้าวโพดหวานต้ม ของว่างแคลต่ำเส้นใยสูง','1787213888255-1342b4fc8309.webp','ภาพโดย Kunal Lakhotia จาก Pexels',120,3,26,1,1,1,'SNACK',1,'2026-08-20 08:18:08','[\"ข้าวโพดหวาน\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (70,'เอดามาเมะนึ่ง','ถั่วแระญี่ปุ่นนึ่งโรยเกลือเล็กน้อย','1787213889327-5b47c8231d7d.webp','ภาพโดย Kei Scampa จาก Pexels',130,11,10,5,1,1,'SNACK',1,'2026-08-20 08:18:09','[\"ถั่วแระญี่ปุ่น\",\"เกลือ\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (71,'แครอทแท่งกับฮัมมัส','แครอทหั่นแท่งจิ้มฮัมมัสถั่วชิกพี','1787213890412-befe4408161b.webp','ภาพโดย Roberto Shumski จาก Pexels',140,5,15,7,1,1,'SNACK',1,'2026-08-20 08:18:10','[\"แครอท\",\"ฮัมมัสถั่วชิกพี\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (72,'ไข่ขาวตุ๋นนมสด','ไข่ขาวตุ๋นเนื้อนุ่มผสมนมสดจืด','1787213891816-458dc2a17426.webp','ภาพโดย Changhee Kim จาก Pexels',160,18,6,6,1,1,'BREAKFAST',1,'2026-08-20 08:18:11','[\"ไข่ขาว\",\"นมสดจืด\",\"ต้นหอม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (73,'สลัดไข่ต้มอะโวคาโด','สลัดไข่ต้มผสมอะโวคาโดหั่นลูกเต๋า น้ำสลัดใส','1787213892975-bc052cea3192.webp','ภาพโดย Medine Dilek Kizmaz จาก Pexels',320,16,14,22,1,0,'LUNCH',1,'2026-08-20 08:18:13','[\"ไข่ต้ม\",\"อะโวคาโด\",\"ผักสลัด\",\"น้ำสลัดใส\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (74,'ข้าวยำปักษ์ใต้','ข้าวยำสมุนไพรปักษ์ใต้ ใส่ผักสดหลากชนิด','1787213894181-3cb8d422624a.webp','ภาพโดย Anna Tarazevich จาก Pexels',350,14,50,10,1,0,'LUNCH',1,'2026-08-20 08:18:14','[\"ข้าวสวย\",\"ตะไคร้ซอย\",\"ถั่วฝักยาว\",\"มะพร้าวคั่ว\",\"น้ำบูดู\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (75,'แกงไตปลาผักรวม ลดกะทิ','แกงไตปลารสจัดจ้าน สูตรลดกะทิ ใส่ผักรวม','1787213895352-0454a6a048d3.webp','ภาพโดย nana liu จาก Pexels',240,18,15,12,0,1,'DINNER',1,'2026-08-20 08:18:15','[\"ไตปลา\",\"พริกแกงไตปลา\",\"ผักรวม (ถั่วฝักยาว/มะเขือ)\",\"ตะไคร้\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (76,'หมูสะเต๊ะย่าง น้ำจิ้มถั่ว','หมูสะเต๊ะย่างเสียบไม้ เสิร์ฟกับน้ำจิ้มถั่วและอาจาด','1787213896704-130635733e1c.webp','ภาพโดย kevin yung จาก Pexels',380,28,20,20,0,0,'LUNCH',1,'2026-08-20 08:18:16','[\"หมูสไลซ์\",\"ผงกะหรี่\",\"กะทิหมัก\",\"น้ำจิ้มถั่ว\",\"อาจาด\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (77,'ไก่ย่างข้าวเหนียวกล้อง','ไก่ย่างสมุนไพร เสิร์ฟกับข้าวเหนียวกล้องแทนขาว','1787213898039-4048264d9b16.webp','ภาพโดย J KREATOR จาก Pexels',460,32,50,12,1,0,'LUNCH',1,'2026-08-20 08:18:18','[\"ไก่ทั้งตัว\",\"สมุนไพรหมัก\",\"ข้าวเหนียวกล้อง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (78,'ปลาหมึกย่างซอสมะนาว','ปลาหมึกย่างราดซอสมะนาวกระเทียมพริก','1787213899299-f71eb5d10bb0.webp','ภาพโดย Thomas Svensson จาก Pexels',220,28,8,7,1,1,'DINNER',1,'2026-08-20 08:18:19','[\"ปลาหมึกสด\",\"กระเทียม/พริก\",\"มะนาว\",\"ผักชี\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (79,'ข้าวผัดกุ้งคลีน','ข้าวผัดกุ้งสูตรคลีน น้ำมันน้อย ใส่ผักรวม','1787213900403-8aed77ff149d.webp','ภาพโดย Roken Manases จาก Pexels',400,24,50,12,1,0,'LUNCH',1,'2026-08-20 08:18:20','[\"กุ้งสด\",\"ข้าวกล้อง\",\"ไข่\",\"ผักรวม\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (80,'ต้มแซ่บกระดูกหมู','ต้มแซ่บกระดูกอ่อนหมู รสจัดจ้านสมุนไพร','1787213901806-b27a559fda8a.webp','ภาพโดย kelvin  agustinus จาก Pexels',260,22,12,14,0,1,'DINNER',1,'2026-08-20 08:18:21','[\"กระดูกอ่อนหมู\",\"ตะไคร้/ใบมะกรูด\",\"พริกป่น\",\"ผักชีฝรั่ง\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (81,'สลัดผักกาดแก้วไก่ย่างเทอริยากิ','ผักกาดแก้วสด ไก่ย่างเทอริยากิหั่นชิ้น','1787213903134-1b0db166a7af.webp','ภาพโดย Bia Metidieri จาก Pexels',340,28,25,12,1,1,'LUNCH',1,'2026-08-20 08:18:23','[\"ผักกาดแก้ว\",\"ไก่ย่างเทอริยากิ\",\"งาขาว\",\"น้ำสลัด\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (82,'ข้าวกล้องแกงมัสมั่นไก่ กะทิน้อย','แกงมัสมั่นไก่สูตรลดกะทิ เสิร์ฟกับข้าวกล้อง','1787213904424-c9d22a6c0b70.webp','ภาพโดย J KREATOR จาก Pexels',420,26,40,16,0,0,'DINNER',1,'2026-08-20 08:18:24','[\"ไก่\",\"พริกแกงมัสมั่น\",\"กะทิ (น้อย)\",\"มันฝรั่ง\",\"ถั่วลิสง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (83,'ยำไข่ดาว','ยำไข่ดาวกรอบ ใส่หอมแดงและพริกขี้หนู','1787213905428-a9f96200d12f.webp','ภาพโดย Medine Dilek Kizmaz จาก Pexels',220,10,12,14,0,1,'LUNCH',1,'2026-08-20 08:18:25','[\"ไข่ดาว\",\"หอมแดง\",\"พริกขี้หนู\",\"มะนาว/น้ำปลา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (84,'น้ำเก๊กฮวยไม่หวาน ข้าวเกรียบธัญพืช','น้ำเก๊กฮวยสูตรไม่หวาน คู่ข้าวเกรียบธัญพืชอบ','1787213906801-98651484b3f5.webp','ภาพโดย Dang Hong จาก Pexels',100,2,18,2,1,1,'SNACK',1,'2026-08-20 08:18:26','[\"ดอกเก๊กฮวย\",\"ข้าวเกรียบธัญพืชอบ\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (85,'มูสช็อกโกแลตอะโวคาโด','มูสช็อกโกแลตเนื้อเนียนจากอะโวคาโด ไม่ใส่ครีม','1787219871604-534524a811bc.webp','ภาพโดย Marcelo Verfe จาก Pexels',180,4,18,11,1,1,'SNACK',1,'2026-08-20 09:57:51','[\"อะโวคาโด\",\"โกโก้ผงไม่หวาน\",\"น้ำผึ้ง\",\"นมอัลมอนด์\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (86,'บราวนี่ถั่วดำไม่ใส่แป้ง','บราวนี่เนื้อหนึบจากถั่วดำ ไม่ใส่แป้งสาลี','1787219872760-952c3075cbab.webp','ภาพโดย Elle Kwee จาก Pexels',160,6,20,7,1,0,'SNACK',1,'2026-08-20 09:57:52','[\"ถั่วดำต้ม\",\"โกโก้ผง\",\"ไข่\",\"น้ำผึ้ง\",\"วานิลลา\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (87,'ไอศกรีมกล้วยไม่ใส่นม','นีซครีมจากกล้วยแช่แข็งปั่น เนื้อเนียนเหมือนไอศกรีม','1787219873867-cc93982d31e8.webp','ภาพโดย Diego Romero จาก Pexels',120,2,28,1,1,1,'SNACK',1,'2026-08-20 09:57:53','[\"กล้วยแช่แข็ง\",\"โกโก้ผง (ไม่บังคับ)\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (88,'เยลลี่ว่านหางจระเข้น้ำผึ้งมะนาว','เยลลี่ว่านหางจระเข้เย็นๆ รสน้ำผึ้งมะนาว','1787219875081-fcd47204c3fe.webp','ภาพโดย kelvin  agustinus จาก Pexels',70,1,16,0,1,1,'SNACK',1,'2026-08-20 09:57:55','[\"วุ้นว่านหางจระเข้\",\"น้ำผึ้ง\",\"มะนาว\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (89,'ขนมปังกล้วยโฮลวีท','ขนมปังกล้วยหอมอบจากแป้งโฮลวีท หอมอบเชย','1787219876170-57ee6fd24e3a.webp','ภาพโดย Gaurav  Sinha จาก Pexels',210,5,34,7,0,0,'SNACK',1,'2026-08-20 09:57:56','[\"กล้วยหอมบด\",\"แป้งโฮลวีท\",\"ไข่\",\"น้ำมันมะพร้าว\",\"อบเชย\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (90,'พุดดิ้งมะพร้าวเจีย','พุดดิ้งเมล็ดเจียแช่กะทิ โรยมะพร้าวขูด','1787219877226-d85742e58fa4.webp','ภาพโดย Farhad Ibrahimzade จาก Pexels',190,5,18,11,1,0,'SNACK',1,'2026-08-20 09:57:57','[\"เมล็ดเจีย\",\"กะทิ\",\"น้ำผึ้ง\",\"มะพร้าวขูด\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (91,'กราโนล่าบาร์โฮมเมด','กราโนล่าบาร์อบเองจากข้าวโอ๊ตและถั่วรวม ไม่ใส่น้ำตาลทราย','1787219878444-1ff1ae5c9c2e.webp','ภาพโดย Jared Kaeb จาก Pexels',170,5,22,7,1,0,'SNACK',1,'2026-08-20 09:57:58','[\"ข้าวโอ๊ต\",\"น้ำผึ้ง\",\"ถั่วรวม\",\"ลูกเกด\",\"เมล็ดฟักทอง\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (92,'เค้กแครอทไม่ใส่น้ำตาล','เค้กแครอทเนื้อชุ่มฉ่ำ หวานจากน้ำผึ้งแทนน้ำตาลทราย','1787219879573-36a67db6ccfa.webp','ภาพโดย Jared Kaeb จาก Pexels',200,4,24,10,0,0,'SNACK',1,'2026-08-20 09:57:59','[\"แครอทขูด\",\"แป้งโฮลวีท\",\"ไข่\",\"อบเชย\",\"น้ำผึ้ง\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (93,'ลูกชุบถั่วเขียวลดหวาน','ลูกชุบถั่วเขียวปั้นสวย สูตรลดน้ำตาล','1787219880968-b31a537f54f3.webp','ภาพโดย YI REN จาก Pexels',140,4,24,3,0,1,'SNACK',1,'2026-08-20 09:58:01','[\"ถั่วเขียวนึ่ง\",\"น้ำตาลลดหวาน\",\"วุ้น\",\"สีผสมอาหารจากธรรมชาติ\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (94,'วุ้นกะทิใบเตยหญ้าหวาน','วุ้นกะทิใบเตยหอมๆ หวานน้อยด้วยหญ้าหวาน','1787219882280-05fd6019680b.webp','ภาพโดย April Miyako จาก Pexels',90,1,14,3,0,1,'SNACK',1,'2026-08-20 09:58:02','[\"วุ้นผง\",\"กะทิ\",\"ใบเตย\",\"หญ้าหวาน\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (95,'ข้าวเหนียวมะม่วงสูตรลดน้ำตาล','ข้าวเหนียวมะม่วงสูตรลดกะทิและน้ำตาล','1787219883381-3851d8f51415.webp','ภาพโดย Dennise Anorico จาก Pexels',280,5,55,5,0,0,'SNACK',1,'2026-08-20 09:58:03','[\"ข้าวเหนียว\",\"มะม่วงสุก\",\"กะทิ (น้อย)\",\"เกลือ\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (96,'คุกกี้อัลมอนด์ไร้แป้ง','คุกกี้แป้งอัลมอนด์ กรอบนอกนุ่มใน ไม่ใส่แป้งสาลี','1787219884558-ec02cafad0ff.webp','ภาพโดย Cook Eat จาก Pexels',150,5,10,11,1,0,'SNACK',1,'2026-08-20 09:58:04','[\"แป้งอัลมอนด์\",\"ไข่\",\"น้ำผึ้ง\",\"วานิลลา\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (97,'เชียร์บาร์ถั่วรวม','เอนเนอร์จี้บาร์อัดแน่นจากถั่วรวมและน้ำผึ้ง','1787219886184-193b9e85c83f.webp','ภาพโดย Bilal Moazzam จาก Pexels',190,6,18,11,1,0,'SNACK',1,'2026-08-20 09:58:06','[\"อัลมอนด์\",\"เม็ดมะม่วงหิมพานต์\",\"น้ำผึ้ง\",\"เมล็ดทานตะวัน\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (98,'โยเกิร์ตกรีกท็อปน้ำผึ้งวอลนัท','โยเกิร์ตกรีกราดน้ำผึ้งและวอลนัทอบ','1787219887554-5f605ff455e3.webp','ภาพโดย Jean-Francois Frenel จาก Pexels',220,14,18,11,1,0,'SNACK',1,'2026-08-20 09:58:07','[\"โยเกิร์ตกรีก\",\"น้ำผึ้ง\",\"วอลนัท\",\"อบเชย\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (99,'แอปเปิลอบอบเชย','แอปเปิลอบทั้งลูกโรยอบเชย หวานธรรมชาติ','1787219888765-2dd540906934.webp','ภาพโดย Piotr Arnoldes จาก Pexels',110,1,26,1,1,1,'SNACK',1,'2026-08-20 09:58:08','[\"แอปเปิล\",\"อบเชย\",\"น้ำผึ้งเล็กน้อย\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (100,'สตรอว์เบอร์รี่จุ่มดาร์กช็อกโกแลต','สตรอว์เบอร์รี่สดจุ่มดาร์กช็อกโกแลต 70%','1787219890065-1a4e03614e41.webp','ภาพโดย Zeynep  Hız จาก Pexels',160,2,20,9,0,0,'SNACK',1,'2026-08-20 09:58:10','[\"สตรอว์เบอร์รี่\",\"ดาร์กช็อกโกแลต 70%\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (101,'มัฟฟินกล้วยข้าวโอ๊ตไม่ใส่แป้ง','มัฟฟินกล้วยหอมข้าวโอ๊ตบด ไม่ใส่แป้งสาลี','1787219891236-a94bcbf91c3f.webp','ภาพโดย zuleyha จาก Pexels',170,6,26,5,1,0,'SNACK',1,'2026-08-20 09:58:11','[\"ข้าวโอ๊ตบด\",\"กล้วยหอม\",\"ไข่\",\"ผงฟู\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (102,'ป๊อปคอร์นโฮลเกรนไม่ใส่เนย','ป๊อปคอร์นอบลมร้อน ไม่ใส่เนยหรือน้ำมัน','1787219892365-c87c81f8f16d.webp','ภาพโดย Elsa Olofsson จาก Pexels',100,3,20,1,1,1,'SNACK',1,'2026-08-20 09:58:12','[\"ข้าวโพดคั่ว\",\"เกลือเล็กน้อย\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (103,'ข้าวซอยไก่ ลดกะทิ','ข้าวซอยไก่สูตรลดกะทิ เส้นบะหมี่กรอบโรยหน้า','1787219893538-c5db90aa4d60.webp','ภาพโดย Vicky Tran จาก Pexels',420,26,45,14,0,0,'LUNCH',1,'2026-08-20 09:58:13','[\"ไก่\",\"พริกแกงข้าวซอย\",\"กะทิ (น้อย)\",\"เส้นบะหมี่\",\"ผักกาดดอง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (104,'ผัดหมี่โคราช ลดน้ำมัน','ผัดหมี่โคราชสูตรน้ำมันน้อย รสเปรี้ยวหวาน','1787219894636-3294a67196ea.webp','ภาพโดย Cook Eat จาก Pexels',380,16,58,9,0,1,'LUNCH',1,'2026-08-20 09:58:14','[\"เส้นหมี่โคราช\",\"หมูสับ\",\"ถั่วงอก\",\"ซอสมะขาม\",\"ไข่\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (105,'หมูปิ้งไม่ติดมัน','หมูปิ้งจากสันในหมัก ไม่ติดมัน ย่างไม่ใช้น้ำมัน','1787219895589-3f7fa8ededc7.webp','ภาพโดย Malte Luk จาก Pexels',220,26,6,10,1,1,'SNACK',1,'2026-08-20 09:58:15','[\"หมูสันในหมัก\",\"กระเทียม\",\"ผักชีราก\",\"น้ำปลา\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (106,'ยำปลาดุกฟู','ปลาดุกฟูกรอบยำกับมะม่วงเปรี้ยว รสจัดจ้าน','1787219896735-c3cfd82e35bf.webp','ภาพโดย Farhad Ibrahimzade จาก Pexels',260,20,15,14,0,0,'LUNCH',1,'2026-08-20 09:58:16','[\"ปลาดุกฟู\",\"มะม่วงเปรี้ยว\",\"พริก\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (107,'สลัดโรลทูน่าอะโวคาโด','สลัดโรลข้าวห่อสาหร่ายไส้ทูน่าและอะโวคาโด','1787219897843-e4599c8f7443.webp','ภาพโดย Farhad Ibrahimzade จาก Pexels',190,14,18,8,1,1,'SNACK',1,'2026-08-20 09:58:17','[\"ทูน่า\",\"อะโวคาโด\",\"แผ่นสาหร่าย\",\"ข้าวสวย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (108,'ซุปเห็ดรวม','ซุปเห็ดรวมน้ำใส ใส่ต้นหอมและพริกไทย','1787219899193-dee4fc204ad7.webp','ภาพโดย Helena Monx จาก Pexels',110,6,12,4,1,1,'DINNER',1,'2026-08-20 09:58:19','[\"เห็ดรวม\",\"ต้นหอม\",\"ซีอิ๊วขาว\",\"พริกไทย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (109,'ผัดคะน้าปลาเค็ม ลดเค็ม','คะน้าผัดปลาเค็มสูตรลดเค็ม กระเทียมพริกหอม','1787219900247-bfa3a4eb34d8.webp','ภาพโดย Kunal Lakhotia จาก Pexels',200,14,10,12,0,1,'DINNER',1,'2026-08-20 09:58:20','[\"คะน้า\",\"ปลาเค็ม (น้อย)\",\"กระเทียม\",\"พริก\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (110,'ข้าวผัดปูคลีน','ข้าวผัดเนื้อปูสูตรคลีน ใช้ข้าวกล้อง','1787219901361-4ff72a8749d7.webp','ภาพโดย Markus Winkler จาก Pexels',400,22,50,12,1,0,'LUNCH',1,'2026-08-20 09:58:21','[\"เนื้อปู\",\"ข้าวกล้อง\",\"ไข่\",\"ต้นหอม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (111,'ต้มโคล้งปลากรอบ','ต้มโคล้งรสจัดจ้าน ใส่ปลากรอบและมะขามเปียก','1787219902461-ab3acc9f579f.webp','ภาพโดย Anna Tarazevich จาก Pexels',200,18,15,7,1,1,'DINNER',1,'2026-08-20 09:58:22','[\"ปลากรอบ\",\"ตะไคร้\",\"ใบมะกรูด\",\"มะขามเปียก\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (112,'แกงคั่วกลิ้งไก่','แกงคั่วกลิ้งไก่สับรสจัดจ้าน สไตล์ปักษ์ใต้','1787219903555-d20a99f01d8f.webp','ภาพโดย Kunal Lakhotia จาก Pexels',280,26,10,16,1,0,'DINNER',1,'2026-08-20 09:58:23','[\"ไก่สับ\",\"พริกแกงคั่วกลิ้ง\",\"ใบมะกรูด\",\"ตะไคร้\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (113,'ยำมะเขือยาว','มะเขือยาวย่างยำกับกุ้งแห้งและหอมแดง','1787219904828-739aa4e8fd03.webp','ภาพโดย Farhad Ibrahimzade จาก Pexels',130,6,14,6,1,1,'LUNCH',1,'2026-08-20 09:58:24','[\"มะเขือยาวย่าง\",\"กุ้งแห้ง\",\"หอมแดง\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (114,'ผัดถั่วงอกเต้าหู้','ถั่วงอกผัดเต้าหู้และกุยช่าย น้ำมันน้อย','1787219905836-718efd3aeb9a.webp','ภาพโดย Kunal Lakhotia จาก Pexels',170,10,14,8,1,1,'DINNER',1,'2026-08-20 09:58:25','[\"ถั่วงอก\",\"เต้าหู้\",\"กุยช่าย\",\"ซีอิ๊วขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (115,'ไก่ห่อใบเตย','อกไก่หมักห่อใบเตยนึ่ง หอมกลิ่นใบเตย','1787219907381-4c539a1fb66d.webp','ภาพโดย Nano Erdozain จาก Pexels',300,28,15,13,1,0,'LUNCH',1,'2026-08-20 09:58:27','[\"อกไก่หมัก\",\"ใบเตย\",\"กระเทียม\",\"พริกไทย\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (116,'ต้มยำปลาน้ำใส','ต้มยำปลากะพงน้ำใส เผ็ดเปรี้ยวสดชื่น','1787219908517-1c4905a7a7ac.webp','ภาพโดย Khải Nguyễn Thanh จาก Pexels',160,20,8,5,1,1,'DINNER',1,'2026-08-20 09:58:28','[\"ปลากะพง\",\"ตะไคร้\",\"ใบมะกรูด\",\"พริกขี้หนู\",\"มะนาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (117,'ข้าวผัดคะน้าไก่','ข้าวผัดคะน้าใส่ไก่สับ กระเทียมหอม','1787219909531-a06115540f2b.webp','ภาพโดย Keegan Evans จาก Pexels',400,24,48,12,0,0,'LUNCH',1,'2026-08-20 09:58:29','[\"ไก่สับ\",\"คะน้า\",\"ข้าวสวย\",\"กระเทียม\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (118,'สลัดอกไก่มะม่วง','สลัดอกไก่ย่างกับมะม่วงดิบซอย รสแซ่บ','1787219910769-f991e1ac2a92.webp','ภาพโดย Ali Dashti จาก Pexels',300,26,25,9,1,1,'LUNCH',1,'2026-08-20 09:58:30','[\"อกไก่ย่าง\",\"มะม่วงดิบซอย\",\"ถั่วลิสงป่น\",\"น้ำปลาหวาน\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (119,'น้ำใบบัวบกไม่หวาน','น้ำใบบัวบกคั้นสด สูตรไม่ใส่น้ำตาล','1787219911887-9aa000bcf3da.webp','ภาพโดย seda güner จาก Pexels',40,1,8,0,1,1,'SNACK',1,'2026-08-20 09:58:31','[\"ใบบัวบก\",\"น้ำเปล่า\",\"หญ้าหวาน\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (120,'น้ำมะพร้าวสด','น้ำมะพร้าวอ่อนสดชื่น ดื่มเย็นๆ','1787219913008-413198417161.webp','ภาพโดย Yiğit  KARAALİOĞLU จาก Pexels',60,0,14,0,1,1,'SNACK',1,'2026-08-20 09:58:33','[\"น้ำมะพร้าวอ่อน\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (121,'สมูทตี้ผักโขมกล้วย','สมูทตี้ผักโขมปั่นกับกล้วยหอมและนมอัลมอนด์','1787219914188-8bea48bd1a52.webp','ภาพโดย elif tekkaya จาก Pexels',190,5,40,3,1,0,'BREAKFAST',1,'2026-08-20 09:58:34','[\"ผักโขม\",\"กล้วยหอม\",\"นมอัลมอนด์\",\"น้ำผึ้ง\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (122,'เต้าฮวยนมสด ลดน้ำเชื่อม','เต้าฮวยนุ่มราดนมสด สูตรลดน้ำเชื่อม','1787219915256-803b0f6de8f5.webp','ภาพโดย SpotwizardLee จาก Pexels',130,8,18,3,0,1,'SNACK',1,'2026-08-20 09:58:35','[\"เต้าฮวย\",\"นมสด\",\"น้ำขิง (ลดหวาน)\"]',1);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (123,'ข้าวเหนียวถั่วดำ','ข้าวเหนียวนึ่งใส่ถั่วดำ โรยงาขาว','1787219916370-ce4bdc708ebb.webp','ภาพโดย J KREATOR จาก Pexels',250,7,50,3,1,0,'BREAKFAST',1,'2026-08-20 09:58:36','[\"ข้าวเหนียว\",\"ถั่วดำต้ม\",\"เกลือ\",\"งาขาว\"]',0);
INSERT INTO `menu_items` (`id`, `name`, `description`, `image_path`, `image_credit`, `calories`, `protein`, `carb`, `fat`, `tag_clean`, `tag_low_cal`, `meal_type`, `is_active`, `created_at`, `ingredients`, `tag_dessert`) VALUES (124,'ปอเปี๊ยะเผือกอบ','ปอเปี๊ยะไส้เผือกบด อบแทนทอด หวานน้อย','1787219917621-3c2ca8693bb9.webp','ภาพโดย Denise  Ailin จาก Pexels',170,4,28,5,0,1,'SNACK',1,'2026-08-20 09:58:37','[\"เผือกนึ่งบด\",\"แผ่นเปาะเปี๊ยะ\",\"น้ำตาลลดหวาน\"]',1);
/*!40000 ALTER TABLE `menu_items` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-08-21  3:21:01
